; Script generated by Gemini for HyperDeck Remote Control Installer

; --- General Setup ---
Name "HyperDeckControl"               ; Name of the installer
OutFile "HyperDeck_Remote_Control_Setup.exe" ; Name of the output installer executable

; Default installation directory (e.g., Program Files/HyperDeckControl)
InstallDir "$PROGRAMFILES\HyperDeckControl"

; The text that appears on the installer's title bar
Caption "HyperDeckControl Setup"

; Icon for the installer executable itself (needs to be an .ico file)
!define MUI_ICON "D:\HyperDeck software\icon.ico"
; Icon for the uninstaller (optional, but good practice)
!define MUI_UNICON "D:\HyperDeck software\icon.ico"

; Request admin privileges for installation (required for Program Files, HKLM)
RequestExecutionLevel admin

; --- Pages (what the user sees during installation) ---
!include "MUI2.nsh"
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

; Optional: Uninstaller page (recommended)
!insertmacro MUI_UNPAGE_WELCOME
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_UNPAGE_FINISH

; --- Languages ---
!insertmacro MUI_LANGUAGE "English"

; --- Installer Sections ---
; IMPORTANT: Define the absolute paths to your PyInstaller 'dist' output folders here.
; These paths should point to the 'app' and 'launcher' folders generated by PyInstaller --onedir.
; Example: If your project root is 'D:\HyperDeck software\MyProject\'
;          and PyInstaller creates 'D:\HyperDeck software\MyProject\dist\app\' and 'dist\launcher\'
;          then you would use:
; !define APP_SOURCE_PATH "D:\HyperDeck software\MyProject\dist\app"
; !define LAUNCHER_SOURCE_PATH "D:\HyperDeck software\MyProject\dist\launcher"
;
; ADJUST THESE PATHS BELOW TO YOUR ACTUAL PYINSTALLER OUTPUT LOCATIONS!
; Note: These paths should NOT have a trailing backslash.
!define APP_SOURCE_PATH "C:\MyProjectInstallerFiles\app" ; <--- ADJUST THIS PATH (NO TRAILING SLASH)
!define LAUNCHER_SOURCE_PATH "C:\MyProjectInstallerFiles\launcher" ; <--- ADJUST THIS PATH (NO TRAILING SLASH)
!define INDEX_HTML_SOURCE_PATH "C:\MyProjectInstallerFiles\index.html" ; <--- ADJUST THIS PATH
!define APP_ICON_SOURCE_PATH "D:\HyperDeck software\icon.ico" ; <--- ADJUST THIS PATH

Section "HyperDeckControl (required)" SecMain

  SetOutPath "$INSTDIR" ; Set the installation output path to the chosen InstallDir

  ; --- DEBUGGING: Show the paths NSIS is trying to use during compilation ---
  !echo "Attempting to copy from: ${APP_SOURCE_PATH}"
  !echo "Attempting to copy from: ${LAUNCHER_SOURCE_PATH}"
  !echo "Attempting to copy from: ${INDEX_HTML_SOURCE_PATH}"
  !echo "Attempting to copy from: ${APP_ICON_SOURCE_PATH}"

  ; --- Copy main application files for NESTED FOLDER STRUCTURE ---
  ; Now using absolute paths AND ensuring the folders themselves are copied (no trailing slash in source).
  ; Copy the entire 'app' folder and its contents recursively
  File /r "${APP_SOURCE_PATH}"          
  ; Copy the entire 'launcher' folder and its contents recursively
  File /r "${LAUNCHER_SOURCE_PATH}"     
  
  File "${INDEX_HTML_SOURCE_PATH}" ; Now using absolute path for index.html
  File "${APP_ICON_SOURCE_PATH}" ; Now using absolute path for application icon

  ; --- Create Uninstaller ---
  WriteUninstaller "$INSTDIR\uninstall.exe"

  ; --- Register Application for Add/Remove Programs (including Publisher) ---
  !define REG_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\HyperDeckControl"
  WriteRegStr HKLM "${REG_UNINST_KEY}" "DisplayName" "HyperDeckControl"
  WriteRegStr HKLM "${REG_UNINST_KEY}" "UninstallString" '"$INSTDIR\uninstall.exe"'
  WriteRegStr HKLM "${REG_UNINST_KEY}" "Publisher" "Neomal Abeyratne"
  WriteRegStr HKLM "${REG_UNINST_KEY}" "InstallLocation" "$INSTDIR"
  WriteRegStr HKLM "${REG_UNINST_KEY}" "DisplayIcon" "$INSTDIR\icon.ico"
  WriteRegStr HKLM "${REG_UNINST_KEY}" "DisplayVersion" "1.8"
  WriteRegStr HKLM "${REG_UNINST_KEY}" "URLInfoAbout" "https://www.blackmagicdesign.com/products/hyperdeckstudio"

  ; --- Create Shortcuts ---
  ; LAUNCHER_EXE_PATH points to launcher.exe inside the 'launcher\' folder after installation.
  !define LAUNCHER_EXE_PATH "$INSTDIR\launcher\launcher.exe"

  ; Create a shortcut on the Desktop
  CreateShortcut "$DESKTOP\HyperDeckControl.lnk" "${LAUNCHER_EXE_PATH}" "" "$INSTDIR\icon.ico" 0

  ; Create a shortcut in the Start Menu
  CreateDirectory "$SMPROGRAMS\HyperDeckControl"
  CreateShortcut "$SMPROGRAMS\HyperDeckControl\HyperDeckControl.lnk" "${LAUNCHER_EXE_PATH}" "" "$INSTDIR\icon.ico" 0
  CreateShortcut "$SMPROGRAMS\HyperDeckControl\Uninstall HyperDeckControl.lnk" "$INSTDIR\uninstall.exe"

SectionEnd

; --- Uninstaller Section ---
Section "Uninstall"

  ; --- Remove Registry Entries for Add/Remove Programs ---
  DeleteRegKey HKLM "${REG_UNINST_KEY}"

  ; Remove shortcuts
  Delete "$DESKTOP\HyperDeckControl.lnk"
  Delete "$SMPROGRAMS\HyperDeckControl\HyperDeckControl.lnk"
  Delete "$SMPROGRAMS\HyperDeckControl\Uninstall HyperDeckControl.lnk"
  RMDir "$SMPROGRAMS\HyperDeckControl" ; Remove Start Menu folder if empty

  ; --- Delete files and directories for NESTED FOLDER STRUCTURE ---
  ; Delete specific files from the root of $INSTDIR
  Delete "$INSTDIR\uninstall.exe"
  Delete "$INSTDIR\index.html"
  Delete "$INSTDIR\icon.ico"
  
  ; Delete the app and launcher folders recursively
  RMDir /r "$INSTDIR\app\"
  RMDir /r "$INSTDIR\launcher\"

  ; Finally, try to remove the main installation directory if it's empty
  RMDir "$INSTDIR"

SectionEnd
